symfonization of activites
PlanningBiblio/PlanningBiblio pull request #209
Opened 2020-09-10 17:42 UTC by sillydebs

2020-09-11 00:09 UTC, jeromecombes requested changes

2020-09-11 00:09 UTC, jeromecombes commented on templates/skill/edit.html.twig
> +          <input type='button' value='Valider' class='ui-button' onclick="location.href='{{ asset('skill.save') }}'" />
remplacer le bouton "Valider" par un submit
\<input type='submit' value='Valider' class='ui-button' />

2020-09-11 00:09 UTC, jeromecombes commented on src/Controller/SkillController.php
> +        $action="ajout";
La variable $action n'est plus utilisée.
La supprimer un peu partout dans le code : controller + template.
Controller : Lignes 74, 80, 95, 102, 114
Template edit : ligne 28

2020-09-11 00:09 UTC, jeromecombes commented on templates/skill/index.html.twig
> +    <input type="hidden" name="page" value='{{ asset("/skill") }}'/>
input page : plus nécessaire

2020-09-11 07:37 UTC, jeromecombes commented on src/Controller/SkillController.php
> +            }
Ignorez ce commentaire sur les redirections.
Le comportement est identique sur les anciennes versions donc on ne le change pas pour le moment.
Le contrôle JS serait un plus mais il pourra être ajouté plus tard.

2020-09-11 09:00 UTC, sillydebs commented on src/Controller/SkillController.php
> +    public function delete_skill(Request $request){
Je crois que delete est un mot déjà utilisé, j'ai eu le même problème avec la classe Position

2020-09-11 10:30 UTC, jeromecombes requested changes

2020-09-11 10:30 UTC, jeromecombes commented on public/setup/atomicupdate/001rename_skills_pages.php
> +require_once(__DIR__ . '../../../include/db.php');
require db.php n'est pas nécessaire dans les fichiers atomicupdate car déjà intégré dans le fichier updatedatabase.php

2020-09-11 10:30 UTC, jeromecombes commented on src/Controller/SkillController.php
> +            'skill_name'=>$nom,
on pourrait simplifier en mettant
'skill_name' => '',
et en supprimant la variable $nom en ligne 74
En bonus : moins de code en français :smile:

2020-09-11 10:30 UTC, jeromecombes commented on src/Controller/SkillController.php
> +                $db->insert("activites", array("nom"=>$nom));
ATTENTION : tu dois maintenant utiliser entityManager, au moins pour les INSERT et UPDATE
Sinon, les entités HTML reviendront car elles sont ajoutés par les fonctions db::insert et db::update.
Tu peux tester en enregistrant un nom comportant des accents

2020-09-11 10:30 UTC, jeromecombes commented on src/Controller/SkillController.php
> +                $db->update("activites", array("nom"=>$nom), array("id"=>$id));
Idem

2020-09-11 10:52 UTC, jeromecombes commented on templates/skill/index.html.twig
> +  <table>
Ajouter la classe CJDataTable, sinon : pas de mise en forme
\<table class='CJDataTable'>

2020-09-11 10:52 UTC, jeromecombes commented on src/Controller/SkillController.php
> +                $db->insert("activites", array("nom"=>$nom));
Je viens de tester et je constate que l'encodage reste correct après insert et update. Donc c'est OK

2020-09-11 12:59 UTC, sillydebs commented on public/setup/atomicupdate/001rename_skills_pages.php
> +require_once(__DIR__ . '../../../include/db.php');
ça m'a affiché une erreur, si je ne le demandais pas, d'où l'inclusion

2020-09-11 13:01 UTC, sillydebs commented on src/Controller/SkillController.php
> +                $db->insert("activites", array("nom"=>$nom));
Je n'ai pas encore intégré l'ORM, je le ferai seulement quand la symfonization sera validée (dixit alex ce matin ^^)

2020-09-11 13:40 UTC, jeromecombes commented on src/Controller/SkillController.php
> +                $db->insert("activites", array("nom"=>$nom));
OK, je suis d'accord. je pensais que les fonctions db::insert et db::update ajoutaient les entités HTML mais ce n'est pas le cas. Donc c'est très bien comme ça.

2020-09-11 13:48 UTC, jeromecombes commented on public/setup/atomicupdate/001rename_skills_pages.php
> +foreach ($db->result as $elem) {
Ajouter avant le foreach :
if ($db->result) {

2020-09-11 14:08 UTC, jeromecombes commented on templates/skill/index.html.twig
> +  <table class='CJDataTable'>
\<table class='CJDataTable' data-sort='[1,"asc"]'>
data-sort : mettra le tri par défaut sur la colonne "nom"

2020-09-14 07:59 UTC, jeromecombes requested changes

2020-09-14 07:59 UTC, jeromecombes commented on templates/skill/index.html.twig
> +        <th data-sort='[1,"asc"]'> Nom de l'activité </th>
data-sort : à mettre sur la balise \<table> (ligne 19) et non sur la \<th>

2020-09-14 08:35 UTC, jeromecombes approved these changes

2020-09-14 08:58 UTC, alexarn commented
Merged on master

2020-09-14 08:58 UTC, closed without merging