doctrinize skills
PlanningBiblio/PlanningBiblio pull request #216
Opened 2020-09-16 14:21 UTC by sillydebs

2020-09-17 12:08 UTC, jeromecombes requested changes

2020-09-17 12:08 UTC, jeromecombes commented on src/Controller/SkillController.php
> +        $query = $this->entityManager->getRepository(Skill::class)->findBy(array('supprime' => NULL));
remplacer
<pre>$query = $this->entityManager->getRepository(Skill::class)->findBy(array('supprime' => NULL));</pre>
par
<pre>$activites = $this->entityManager->getRepository(Skill::class)->findBy(array('supprime' => NULL));</pre>

Et supprimer les lignes 27 à 33 ($activites = array(); ... If ... foreach {}}

2020-09-17 14:03 UTC, jeromecombes approved these changes

2020-09-18 07:57 UTC, alexarn commented
Merged on master

2020-09-18 07:57 UTC, closed without merging