Symfonize attendance hours' edition and save
PlanningBiblio/PlanningBiblio pull request #255
Opened 2020-10-27 14:03 UTC by sillydebs

2020-12-02 13:37 UTC, alexarn requested changes
The link for adding working is wrong (attendance/add => workinghour/add).
In the same URL, the parameter retour is "index.php". Shouldn't it be 'workinghour ?'

Please rebuild this PR on master. Back links are on the former index page

2020-12-02 13:41 UTC, alexarn requested changes
Link on my account is the former one

2020-12-02 18:10 UTC, sillydebs commented
Main issues were :
- wrong link in monCompte.php 
- wrong parameters or variables for "retour" or href in template

Corrections are done and I force-pushed due to the rebase I did 2 hours ago.

2020-12-03 07:54 UTC, alexarn requested changes
- Back link is wrong. Please test. click on add workinghours, click on back (retour) => fail

- from my account, the link to working hours is denied (workingHour)

- Total hours are not calculated at the fly

- i can save workinghours for the same agent on the period. We should have an ajax control

- when i create new exception, the table is not pre-filled with the current hours. It's empty

2020-12-03 08:23 UTC, sillydebs commented
Many files have been corrupted after my attempt to restore the branch. I will fix it ASAP.

2021-01-08 09:00 UTC, alexarn requested changes
AttendanceController and attendance/edit.html.twig are not needed imo

2021-01-08 15:58 UTC, alexarn requested changes
Missing atomic update for removing access

Critical issue: sites are not kept in the working hours form

2021-01-08 15:58 UTC, alexarn commented on public/monCompte.php
> +    <a href='/workinghour/add?retour=monCompte.php' class='ui-button'>
Please add $config['URL']

2021-01-08 15:58 UTC, alexarn commented on public/monCompte.php
> +        echo "<td style='white-space:nowrap;'>$arrow <a href='/workinghour/{$elem['id']}?retour=monCompte.php'/>";
Please add $config['URL']

2021-01-08 15:58 UTC, alexarn commented on public/planningHebdo/js/script.planningHebdo.js
> +      url: "/workinghour",
Please add baseURL

2021-01-18 15:19 UTC, alexarn requested changes
"Parse error: syntax error, unexpected 'echo' (T_ECHO), expecting ';' or ',' in /home/plb/planningBiblio/public/monCompte.php on line 97" when going to my account

2021-01-18 15:23 UTC, alexarn commented on public/setup/atomicupdate/removePaths.php
> +$sql[]="DELETE FROM `{$dbprefix}acces` WHERE `page` LIKE '%planningHebdo%'";
You need to remove the route /workinghour

2021-01-18 15:34 UTC, alexarn requested changes
Other issue:
  - Set PlanningHebdo-Validation-N2 to 1
  - Add new workinghour for an agent
  - Set status to "Accepted (waiting for ....)"
  - Save
  - Edit the workinghour
    => No option accepted in status

2021-01-20 09:07 UTC, alexarn approved these changes

2021-01-20 09:07 UTC, alexarn commented
Merged on master

2021-01-20 09:07 UTC, closed without merging