Symfonize planning/postes_cfg/modif.php
PlanningBiblio/PlanningBiblio pull request #263
Opened 2020-11-06 09:19 UTC by sillydebs

2020-11-09 13:53 UTC, sillydebs commented on public/include/function.php
> +function myselectHeure($min, $max, $blank=false)
I created a new function to manage select options when the user chooses hours for their table.

2020-11-09 13:53 UTC, sillydebs commented on public/planning/postes_cfg/ajax.infos.php
> +$nom=filter_input(INPUT_GET, "nom");
The last parameter has been removed to prevent html entities when adding quotes.

2020-11-09 13:55 UTC, sillydebs commented on src/Controller/FrameworkController.php
> +                        }
Indentation was wrong here, so I had to correct it.

2020-11-09 13:57 UTC, sillydebs commented on src/Controller/FrameworkController.php
> +            return $this->redirectToRoute('framework.edit_table', array("id" => $tableauNumero, "cfg-type"=> $post['cfg-type'], "msg" => $msg, "msgType" => $msgType));
I noticed after most of my corrections that I could not use Flashbags to inform the user, thus I chose to return the message through the URL as legacy code did with a script tag.

2020-11-09 13:58 UTC, sillydebs commented on templates/framework/edit_tab.html.twig
> +                        </select>
Correction has been done following changes on myselectHeures function.

2021-01-20 13:22 UTC, alexarn requested changes
You may need to re-apply your changes on a fresh master

2021-01-20 13:22 UTC, alexarn commented on public/planning/postes_cfg/copie.php
> +        echo "<script type='text/javaScript'>parent.location.href='/framework/$numero?cfg-type=horaires';</script>\n";
please use $config['url']

2021-01-20 13:22 UTC, alexarn commented on public/planning/postes_cfg/copie.php
> +    echo "<script type='text/javaScript'>parent.location.href='/framework?cfg-type=horaires&numero=$numero2';</script>\n";
Use $config['url']

2021-01-20 13:22 UTC, alexarn commented on public/planning/postes_cfg/js/tableaux.js
> +      url: "/planning/postes_cfg/ajax.supprimeLigne.php",
please use BASEUrl

2021-01-20 13:22 UTC, alexarn commented on public/planning/postes_cfg/js/tableaux.js
> +      url: "/planning/postes_cfg/ajax.supprimeTableau.php",
Use baseurl

2021-01-20 13:22 UTC, alexarn commented on public/planning/postes_cfg/js/tableaux.js
> +    url: "/planning/postes_cfg/ajax.infos.php",
use baseurl

2021-01-20 13:22 UTC, alexarn commented on public/planning/postes_cfg/js/tableaux.js
> +      url: "/planning/postes_cfg/ajax.recupTableau.php",
use baseurl

2021-01-20 13:22 UTC, alexarn commented on public/planning/postes_cfg/lignes_sep.php
> +    echo "<script type='text/JavaScript'>document.location.href='/framework'</script>\n";
use $config['url']

2021-01-20 13:22 UTC, alexarn commented on public/planning/postes_cfg/lignes_sep.php
> +    echo "<script type='text/JavaScript'>document.location.href='/framework'</script>\n";
use $config['url']

2021-01-20 13:22 UTC, alexarn commented on public/setup/atomicupdate/newPaths.php
> +$sql[]="UPDATE `{$dbprefix}menu` SET `url` = '/framework' WHERE `url` = 'planning/postes_cfg/index.php';";
You can delete this file since framework index is pushed master

2021-01-20 13:22 UTC, alexarn commented on public/setup/atomicupdate/removePath.php
> +$sql[]="DELETE FROM `{$dbprefix}acces` WHERE `page` = 'planning/postes_cfg/modif.php';";
Keep this entry with an empty page

2021-01-20 13:22 UTC, alexarn commented on public/setup/db_data.php
> +$sql[]="INSERT INTO `{$dbprefix}acces` (`nom`,`groupe_id`,`groupe`,`page`,`categorie`,`ordre`) VALUES ('Configuration des tableaux', 22, 'Configuration des tableaux', '/framework','Planning',140);";
You can remove this change

2021-01-20 13:22 UTC, alexarn commented on public/setup/db_data.php
> -$sql[]="INSERT INTO `{$dbprefix}acces` (`nom`,`groupe_id`,`groupe`,`page`,`categorie`,`ordre`) VALUES ('Configuration des tableaux - Modif',22,'Configuration des tableaux','planning/postes_cfg/modif.
keep this entry with an empty page

2021-01-20 13:22 UTC, alexarn commented on src/Controller/FrameworkController.php
> +     * @Route ("/framework", name="framework.index", methods={"GET"})
This method/route is now on master

2021-01-22 11:11 UTC, alexarn requested changes
Edit a table. Save. We are redirected to /framework/tab-<id>. Why tab-<id> ? This empty the form ...

On the lines tab, lines are not shown. We have a default table (tableau 1) created at installation time and which has lot of line. There is no line shown here. Only table headers

There is also encoding issue in table headers

I can't add line. Clicking on the green plus sign on table header doesn't work

2021-01-22 11:11 UTC, alexarn commented on public/setup/db_data.php
> +$sql[]="INSERT INTO `{$dbprefix}acces` (`nom`,`groupe_id`,`groupe`,`page`,`categorie`,`ordre`) VALUES ('Configuration des tableaux', 22, 'Configuration des tableaux', '','Planning',140);";
Why are you adding this entry ?

2021-01-22 11:11 UTC, alexarn commented on src/Controller/FrameworkController.php
> +require_once(__DIR__ . '/../../public/include/config.php');
Why including config.php ?

2021-01-22 13:06 UTC, alexarn requested changes
Redirect to tab-<id> is not corrected

2021-01-22 13:06 UTC, alexarn commented on src/Controller/FrameworkController.php
> +            return $this->redirect('/framework/'.$tableauNumero.'?cfg-type='.$post['cfg-type'].'&msg='.$msg.'&msgType='.$msgType);
IMO redirectToRoute is better

2021-02-09 10:20 UTC, alexarn requested changes
Create a position with apostrophe
Add this position to a framework table => bad encoding

2021-02-10 10:17 UTC, alexarn requested changes

2021-02-10 10:17 UTC, alexarn commented on templates/framework/index.html.twig
> -      <input type='submit' value='Nouvelle ligne' class='ui-button' onclick='location.href="{{ asset('framework-line/add') }}";'/>
You remove here a good link

2021-02-10 10:17 UTC, alexarn commented on templates/framework/index.html.twig
> +      <input type='hidden' name='page' value='planning/postes_cfg/lignes_sep.php' />
You add here a wrong link

2021-03-23 09:51 UTC, alexarn commented
Script planning/postes_cfg/modif.php no longer exist in master. I think the work here has already been merged on master.
Close this pull request

2021-03-23 09:51 UTC, closed without merging