MT 31000 - Take in account empty site in agent's times in holiday validation workflow
PlanningBiblio/PlanningBiblio pull request #303
Opened 2020-12-17 14:44 UTC by alexarn

Retrieving site number from agents times could bring an empty value. This can happen when validating holiday on a period whose at least one day has no site set (i.e a saturday: ['', '', '', '']).

According to PHP version or configuration, <?php 400 + '' ?> can just warn or ... crash.

This path fix that

2020-12-18 07:14 UTC, jeromecombes requested changes

2020-12-18 07:14 UTC, jeromecombes commented on public/conges/class.conges.php
>                          $site=$temps[$offset][4];
Pour le contrôle, je conseille de remplacer ceci :
<pre>if (array_key_exists(4, $temps[$offset]) && $temps[$offset][4]) {</pre>
par ceci
<pre>if (!empty($temps[$offset][4])) {</pre>

2020-12-21 14:39 UTC, jeromecombes approved these changes

2020-12-22 14:47 UTC, alexarn commented
Merged on master, 20.10.xx and 20.04.xx

2020-12-22 14:47 UTC, closed without merging