Write ICS URL from base URL (20.10.xx)
PlanningBiblio/PlanningBiblio pull request #330
Opened 2021-01-28 09:41 UTC by alexarn

2021-01-28 21:11 UTC, jeromecombes requested changes

2021-01-28 21:11 UTC, jeromecombes commented on public/js/script.js
> +      url: "/ics/ajax.resetURL.php",
Please use baseURL
`url: baseURL + "/ics/ajax...`

2021-01-29 11:54 UTC, jeromecombes approved these changes

2021-02-11 16:18 UTC, alexarn commented
Merged on 20.10.xx

2021-02-11 16:18 UTC, closed without merging