MT 31736 Use config URL from planning url notification (master and 20.10.xx)
PlanningBiblio/PlanningBiblio pull request #385
Opened 2021-03-05 10:08 UTC by alexarn

2021-03-05 13:43 UTC, jeromecombes requested changes

2021-03-05 13:43 UTC, jeromecombes commented on public/planning/poste/class.planning.php
> +                $url = $config['URL'] . "/index.php?page=planning/poste/index.php&date=$date");
Il faut retirer la parenthèse fermante

2021-03-05 13:43 UTC, jeromecombes commented on public/planning/poste/class.planning.php
> +                $url = $config['URL'] . "/index.php?page=planning/poste/index.php&date=$date");
Retirer la parenthèse fermante

2021-03-08 09:28 UTC, alexarn commented
Merged on master and 20.10.xx
Available for 20.10.06

2021-03-08 09:28 UTC, closed without merging