Symfonize table restore
PlanningBiblio/PlanningBiblio pull request #397
Opened 2021-03-23 14:45 UTC by alexarn

2021-04-02 14:13 UTC, jeromecombes requested changes

2021-04-02 14:13 UTC, jeromecombes commented on public/js/framework.js
>  /**
This file should go to public/js/**plb**

We want to separate our JS files from vendor files (that will probably go to public/js/vendor)

2021-04-02 14:13 UTC, jeromecombes commented on public/cron.ctrlPlanning.php
This file should go to /src/Cron/Legacy/
and $path should be remplaced by \__DIR__ . '/../../../public'

2021-04-02 14:28 UTC, jeromecombes commented
Lors d'un test de restauration d'un tableau, après avoir  :
- utilisé le tableau sur 2 journées, une validée, l'autre nom (je ne pense pas qu'il y ait un impact à ce niveau)
- supprimé le tableau
- supprimé un poste associé à ce tableau (qu'il est censé restaurer)
- supprimé une activité associé au poste (qu'il est censé restaurer)

J'ai l'erreur en popup : "Une erreur est survenue lors de la récupération du tableau "[nom du tableau] (utilisation : 02/04/2021)".

2021-04-09 08:51 UTC, alexarn commented
> Lors d'un test de restauration d'un tableau, après avoir :
> 
> * utilisé le tableau sur 2 journées, une validée, l'autre non (je ne pense pas qu'il y ait un impact à ce niveau)
> * supprimé le tableau
> * supprimé un poste associé à ce tableau (qu'il est censé restaurer)
> * supprimé une activité associé au poste (qu'il est censé restaurer)
> 
> J'ai l'erreur en popup : "Une erreur est survenue lors de la récupération du tableau "[nom du tableau] (utilisation : 02/04/2021)".

 - J'ai créé un nuveau tableau "Tableau de test", puis un poste "Poste de test" et une activité "Activité de test".
 - j'ai ajouté l'activité de test au poste de test, puis le poste de test au tableau de test.
 - J'ai utilisé le tableau jeudi 8 et validé
 - J'ai utilisé le tableau vendredi 9. Sans valider.
 - J'ai supprimé le tableau, supprimé le poste et l'ativité.
 - La récupération a fonctionné.

2021-04-16 07:57 UTC, jeromecombes commented
J'ai toujours l'erreur lors de la restauration des tableaux supprimés.

En ouvrant la console JS, je vois l'erreur 403 Forbidden sur la page Ajax /framework/restore_table
En regardant le détaille dans la console, la requête Ajax /framework/restore_table renvoie une page HTML avec le message "Accès refusé" avecl'entête et le pied de page Planning Biblio.

2021-04-16 08:05 UTC, jeromecombes requested changes

2021-04-16 08:05 UTC, jeromecombes commented on src/Cron/Legacy/cron.ctrlPlanning.php
>  // Génération d'un CSRF Token
TEST : 
<pre>PHP Warning:  session_start(): Cannot start session when headers already sent in /var/www/html/plb/src/Cron/Legacy/cron.ctrlPlanning.php on line 44</pre>

En supprimant session_start(); en ligne 44 : ça passe, et le reçoit bien les mails.

2021-04-16 08:21 UTC, jeromecombes requested changes
Lors de la restauration des tableaux, les postes et activités associés aux tableaux qui ont été supprimés ne sont pas restaurés.
Les lignes (postes) apparaissent bien dans les tableaux sur la page Planning mais :
- elles sont vides sur la configuration des tableaux (onglet lignes)
- les postes n'apparaissent pas sur la page administration / les postes
- les activités n'apparaissent pas sur la page administration / les activités

2021-04-21 15:22 UTC, jeromecombes approved these changes

2021-04-22 09:33 UTC, alexarn commented
Merged on master

2021-04-22 09:33 UTC, closed without merging