Mark leaved agents as crossed off when importing models
PlanningBiblio/PlanningBiblio pull request #404
Opened 2021-03-26 15:23 UTC by alexarn

2021-04-02 08:09 UTC, jeromecombes requested changes

2021-04-02 08:09 UTC, jeromecombes commented on public/planning/poste/fonctions.php
> +                if ($elem['depart'] > '0000-00-00' && $elem['depart'] <= $date) {
On the departure date, the agent is still working

Change this line for 
<pre>if ($elem['depart'] > '0000-00-00' && $elem['depart'] < $date) {</pre>

2021-04-02 08:16 UTC, jeromecombes commented on public/planning/poste/fonctions.php
> +                if ($elem['depart'] > '0000-00-00' && $elem['depart'] <= $date) {
Solved here 7daf8ce5ce069d00033cea6ad2439bbcfe862ec6

2021-04-02 08:16 UTC, jeromecombes approved these changes

2021-04-06 13:35 UTC, alexarn commented
Merged on master and 20.10.xx

2021-04-06 13:35 UTC, closed without merging