Symfonize admin index
PlanningBiblio/PlanningBiblio pull request #412
Opened 2021-04-21 09:41 UTC by alexarn

2021-04-21 14:42 UTC, jeromecombes requested changes

2021-04-21 14:42 UTC, jeromecombes commented on templates/admin/index.html.twig
> +      <li><a href='{{ asset("closingday") }}'>Jours de fermeture</a></li>
For closingdays :
<pre>{% if userCan('25') %}</pre>

2021-04-21 14:52 UTC, jeromecombes requested changes

2021-04-21 14:52 UTC, jeromecombes commented on templates/admin/index.html.twig
> +    {% if userCan('1101') and config('PlanningHebdo') %}
userCan('1101') does not work.
Do what you've done for models

2021-04-21 15:01 UTC, jeromecombes commented on templates/admin/index.html.twig
> +    {% if userCan('1101') and config('PlanningHebdo') %}
fixed with 9c39534d0ddb84423da051cd17ebe0425e27eedc

2021-04-21 15:02 UTC, jeromecombes commented on templates/admin/index.html.twig
> +      <li><a href='{{ asset("closingday") }}'>Jours de fermeture</a></li>
fixed with 9c39534

2021-04-21 15:02 UTC, jeromecombes approved these changes

2021-04-22 09:49 UTC, alexarn commented
Merged on master

2021-04-22 09:49 UTC, closed without merging