Symfonyze menu div - Step 1: move html code from ajax.menudiv.php to planning.js
PlanningBiblio/PlanningBiblio pull request #433
Opened 2021-05-06 08:43 UTC by alexarn

2021-05-20 13:30 UTC, jeromecombes requested changes

2021-05-20 13:30 UTC, jeromecombes commented on public/planning/poste/js/planning.js
> +console.log(result);
console.log must be removed.

2021-05-20 13:32 UTC, jeromecombes commented
With config Planning / Planning-Heures not checked : 
The menu is not diplayed.
JS Error : 
<pre>Uncaught TypeError: agent.times is undefined</pre>

2021-05-20 13:36 UTC, jeromecombes commented
With config Planning / Planning-Absences-Heures-Hebdo checked
The menu is not displayed
JS error : 
<pre>Uncaught SyntaxError: expected expression, got '<'</pre>

2021-05-20 14:58 UTC, jeromecombes commented
Les accents s'affichent en entités HTML dans les info-bulles

2021-05-27 14:59 UTC, jeromecombes commented
> With config Planning / Planning-Absences-Heures-Hebdo checked
> The menu is not displayed
> JS error :
> 
> Uncaught SyntaxError: expected expression, got '<'

To reproduce : 
- set APP_DEBUG = 1 in .env.local
- check config Planning / Planning-Absences-Heures-Hebdo
- create an absence for one agent for one day in the week you are working on
- make sure that this agent does not have working hours for the week you are working on
- right-click on the planning : the contextual menu does not appear and the top menu is displayed on footer

1./ The function that returns working hours to compute the quota may return a non-numeric value that generates an error in this case. Take it into consideration or make the function returns 0 when there is no working hours.

2./ The ajax script seems to return HTML code which is displayed on the main page when an error happens. Try to catch errors and use CJInfo to display a warning message.

2021-06-04 15:48 UTC, jeromecombes approved these changes

2021-06-07 08:37 UTC, alexarn commented
Merged on master

2021-06-07 08:37 UTC, closed without merging