Replace use of app.request.getBaseURL() with app.request.getSchemeAndHttpHost() in templates
PlanningBiblio/PlanningBiblio pull request #442
Opened 2021-05-19 09:44 UTC by alexarn

With Symfony 3.4, getBaseURL always return empty. We should use getSchemeAndHttpHost instead.

2021-05-20 07:21 UTC, jeromecombes requested changes
Please use the asset function
e.g. : 
<pre><script type='text/JavaScript' src='{{ asset("absences/js/modif.js") }}?version={{ version }}'></script></pre>

2021-05-20 07:21 UTC, jeromecombes commented on templates/absences/add.html.twig
>  {% endblock %}
You should use "asset" : 
<pre>
<script type='text/JavaScript' src='{{ asset("absences/js/modif.js") }}?version={{ version }}'></script>
</pre>

2021-05-20 20:06 UTC, jeromecombes requested changes

2021-05-20 20:06 UTC, jeromecombes commented on public/conges/js/script.conges.js
line 411
<pre>
- baseURL = '';
+ baseURL = '/';
</pre>

2021-05-21 09:13 UTC, jeromecombes approved these changes

2021-05-26 08:00 UTC, alexarn commented
Merged on master

2021-05-26 08:00 UTC, closed without merging