Symfonize agent deletion
PlanningBiblio/PlanningBiblio pull request #445
Opened 2021-05-26 15:46 UTC by alexarn

Replace PR #297

2022-09-19 13:57 UTC, jeromecombes commented
Suivi : voir MT 38207

2022-10-03 15:00 UTC, alexarn commented
Rebased on master

2022-11-08 09:04 UTC, jeromecombes requested changes

2022-11-08 09:04 UTC, jeromecombes commented on templates/agents/index.html.twig
> +                }
Les enchaînements ne sont pas logiques (je n'ai pas reproduit en tests, il faut reproduire une erreur pour vérifier complétement) : 
1./ Affiche un message success en popup
2./ ferme la dailogbox
3./ reload la page.
Les actions 1 et 2 semblent inutiles du fait du rechargement de la page et le message sera à peine visible.
Utiliser les flash bags

2022-11-08 09:04 UTC, jeromecombes commented on templates/agents/index.html.twig
> +              }
Les enchaînements ne sont pas logiques (je n'ai pas reproduit en tests, il faut reproduire une erreur pour vérifier complétement) : 
1./ Affiche un message success en popup
2./ ferme la dailogbox
3./ reload la page.
Les actions 1 et 2 semblent inutiles du fait du rechargement de la page et le message sera à peine visible.
Utiliser les flash bags

2022-11-08 09:21 UTC, jeromecombes commented on templates/agents/index.html.twig
> +              data : {id: id, CSRFToken: CSRFToken, date: date, hasDate: hasDate},
J'ajoute  que sur master nous n'avons aucune mention de has-date et hasDate
`planningb@planno:~/www/planningbiblio$ grep -ri --exclude-dir={vendor,.git,var,jquery-ui-1.11.2} "hasDate" *`
`planningb@planno:~/www/planningbiblio$ grep -ri --exclude-dir={vendor,.git,var} "has-date" *`
`planningb@planno:~/www/planningbiblio$ grep -ri --exclude-dir={vendor,.git,var} "c-text" *`

2022-12-10 10:45 UTC, jeromecombes commented on templates/agents/index.html.twig
> +  <div id='confirmation'style="display: none;">
corrigé avec c616f8a58094557799cf973e8aac3b1470b3e377

2022-12-10 10:46 UTC, jeromecombes commented on templates/agents/index.html.twig
> +              data : {id: id, CSRFToken: CSRFToken, date: date, hasDate: hasDate},
corrigé avec c616f8a58094557799cf973e8aac3b1470b3e377
Ce commit supprime toute référence hasDate has-date et contrôle si le param existe avec $date !== null

2022-12-21 07:25 UTC, jeromecombes commented
Rebased on master

2022-12-21 07:29 UTC, jeromecombes commented on templates/agents/index.html.twig
> +      <form method='delete' action="{{ asset('/agent') }}" name='form' onsubmit='verif_form("date=date");'>
Correction en cours (21/12/2022)

2022-12-21 07:42 UTC, jeromecombes commented on templates/agents/index.html.twig
> +    <form name='form' id='confirmation-form' action="{{ asset('/agent') }}"  method='delete'>
Correction en cours (21/12/2022)

2022-12-21 10:23 UTC, jeromecombes commented on templates/agents/index.html.twig
> +            $('#confirmation-form').method = "delete";
Corrigé par 9c2ff5155ccd9b05d2b4dde2b9c047a9ebeed192

2022-12-21 10:23 UTC, jeromecombes commented on templates/agents/index.html.twig
> +    <form name='form' id='confirmation-form' action="{{ asset('/agent') }}"  method='delete'>
corrigé par 9c2ff5155ccd9b05d2b4dde2b9c047a9ebeed192

2022-12-21 10:24 UTC, jeromecombes commented on templates/agents/index.html.twig
> +      <form method='delete' action="{{ asset('/agent') }}" name='form' onsubmit='verif_form("date=date");'>
corrigé par 9c2ff5155ccd9b05d2b4dde2b9c047a9ebeed192

2022-12-21 10:24 UTC, jeromecombes commented on templates/agents/index.html.twig
> +                }
corrigé par 9c2ff5155ccd9b05d2b4dde2b9c047a9ebeed192

2022-12-21 10:24 UTC, jeromecombes commented on templates/agents/index.html.twig
> +                CJInfo("Une erreur est survenue lors de la suppression","error");
corrigé par 9c2ff5155ccd9b05d2b4dde2b9c047a9ebeed192

2022-12-21 10:24 UTC, jeromecombes commented on templates/agents/index.html.twig
> +                }
corrigé par 9c2ff5155ccd9b05d2b4dde2b9c047a9ebeed192

2022-12-21 10:34 UTC, jeromecombes commented on templates/agents/index.html.twig
> +              }
corrigé par 9c2ff5155ccd9b05d2b4dde2b9c047a9ebeed192

2022-12-21 11:08 UTC, jeromecombes approved these changes
revue : OK avec les commits du jour
tests : OK
PR approuvée pour master
à squasher

2022-12-21 11:15 UTC, jeromecombes commented
Replaced with #822

2022-12-21 11:15 UTC, closed without merging