Symfonise absence edition
PlanningBiblio/PlanningBiblio pull request #471
Opened 2021-07-21 08:41 UTC by alexarn

2021-08-20 13:01 UTC, jeromecombes commented on src/Controller/AbsenceController.php
> +        // FIXME seems we never pass in here.
But the check is not complete :
attachments are not checked.

2022-09-19 13:47 UTC, jeromecombes commented
Test plan : 
- créer et modifier des absences
- bien vérifier les modifications des absences (cette PR ne concerne que les modifications, pas les ajouts)
- vérifier le bon fonctionnement de l'ensemble
- faire différents tests avec plusieurs paramètres différents (un agent, pour moi, pour d'autres, admin, pas admin, plusieurs agents, valider
- validation : demandée, accepter niveau 1, refuser niveau 1, accepté niveau 2, refusé niveau 2
- récurrences : avec et sans, si avec : modifier toutes, seulement celle-ci, celle-ci et les suivantes
- pièces jointes : avec et sans.
- changer les dates
- changer les agents

tester avec plusieurs profiles (pas de droit de gestion des absences, droit de validation niveau 1, droit de validation niveau 2)

Faire les tests avec les différentes config : 
- Absences-validation : cochée et décochée
- Absences-planningVide : cochée et décochée (comparaison avec absence sur des plannings en cours d'élaboration ou non-commencés, ou validés)
- Absences-apresValidation : cochée et décochée (comparaison avec absence sur des plannings validés ou non)
- Absences-Validation-N2 : cochée et décoché (si décochée : on ne doit pas pouvoir valider au niveau 2 si pas de validation niveau 1 avant)
- mono / multi-sites

Comparer le fonctionnement avec master

2022-10-04 13:23 UTC, alexarn commented
Rebased on master

2022-10-05 13:22 UTC, jeromecombes requested changes
Les tests fonctionnels ne sont pas concluant.
Dans de nombreux cas, les absences ne sont pas modifiées après soumission du formulaire.
Voir MT38442

2022-10-26 07:34 UTC, jeromecombes commented
> Les tests fonctionnels ne sont pas concluant. Dans de nombreux cas, les absences ne sont pas modifiées après soumission du formulaire. Voir MT38442

Corrigé par le commit 66898a15872569100f0c2c607da1c08bc07b6e49

2022-10-26 07:36 UTC, jeromecombes approved these changes

2022-11-07 09:17 UTC, jeromecombes commented
PR approuvée pour master

2022-11-07 12:45 UTC, alexarn commented
Megred on master

2022-11-07 12:45 UTC, closed without merging