Add clear-string class on datatable columns that needs sort on accents
PlanningBiblio/PlanningBiblio pull request #516
Opened 2021-11-18 15:41 UTC by alexarn

2021-11-18 17:29 UTC, dogirod commented on public/js/CJScript.js
> +    .replace(/[áãà]/g, 'a')
manquent äâ

2021-11-18 17:29 UTC, dogirod commented on public/js/CJScript.js
> +    .replace(/[íï]/g, 'i')
manque î

2021-11-18 17:29 UTC, dogirod commented on public/js/CJScript.js
> +    .replace(/[óõô]/g, 'o')
manque ö

2021-11-18 17:29 UTC, dogirod commented on public/js/CJScript.js
> +    .replace(/[úü]/g, 'u')
manque û

2021-11-18 17:59 UTC, jeromecombes commented
@alexarn Il existe déjà une fonction removeAccents dans js/script.js
Si tu peux l'utiliser pour ici, ça permettra d'éviter les oublis (cf commentaires @dogirod )

2021-11-19 14:57 UTC, jeromecombes requested changes
Tests rapide (avec les é) : 
--> marche bien.

Dominique a remarqué qu'il y avait des manques.
Et j'ai remarqué qu'il y avait déjà une fonction removeAccents, sans doute plus complète ou qui pourrait être complétée.
Il serait intéressant d'utiliser une fonction centrale pour la suppression des accents pour éviter les oublis. @alexarn Vois si tu peux l'utiliser.

2021-11-19 15:22 UTC, alexarn commented
Merged on master

2021-11-19 15:22 UTC, closed without merging