Check defined array keys in workinghour table
PlanningBiblio/PlanningBiblio pull request #531
Opened 2021-12-07 15:37 UTC by alexarn

2022-02-02 15:26 UTC, jeromecombes approved these changes
testée et approuvée.

2022-02-03 07:32 UTC, jeromecombes requested changes
KO : 
Si on vérifie les heures de présence enregistrées après validation, on constate que toutes les cellules timepicker laissées vides affichent la date à laquelle le planning a été enregistré.

Ceci n'est pas constaté sur master.

2022-02-04 16:20 UTC, jeromecombes approved these changes
revue et tests des 2 commits : OK
PR approuvée

2022-02-07 08:24 UTC, alexarn commented
Merged on master and 21.10.xx

2022-02-07 08:24 UTC, closed without merging