Always set absence hours like h:m:s
PlanningBiblio/PlanningBiblio pull request #539
Opened 2022-01-06 10:00 UTC by alexarn

Test plan: see MT 35366

2022-01-06 10:51 UTC, jeromecombes requested changes

2022-01-06 10:51 UTC, jeromecombes commented on public/absences/class.absences.php
> +
Est-ce que les lignes 1371 à 1374 sont utiles ?
Ces variables sont traitées dans build_ics_content et je le les retrouve pas dans la fonction ics_add_event.

2022-01-06 10:53 UTC, jeromecombes commented on public/absences/class.absences.php
> +
@alexarn Ignore le commentaire précédent.
Elles sont utiles à la génération de la variable $uid utilisée en ligne 1384

2022-01-19 18:06 UTC, jeromecombes approved these changes

2022-01-27 11:15 UTC, alexarn commented
Merged on master and 21.10.xx

2022-01-27 11:15 UTC, closed without merging