Force end hour to 23:59:59 when allday is checked
PlanningBiblio/PlanningBiblio pull request #568
Opened 2022-02-07 15:52 UTC by alexarn

Test plan:
  - Create an absence or holiday,
  - Status "asked", allday checked
  - Save
  - Edit the absence / holiday
  - Status "Accepted"
  - Save
  - Edit it again. 
  => the allday is uncheked.

2022-02-08 09:29 UTC, alexarn commented
Fix applied on #471

2022-03-11 10:36 UTC, alexarn commented
Seems that this PR should be ignored and replaced with #587

2022-03-11 14:42 UTC, jeromecombes requested changes

2022-04-14 07:53 UTC, alexarn commented
Replaced with #587

2022-04-14 07:53 UTC, closed without merging