MT29957: Password complexity
PlanningBiblio/PlanningBiblio pull request #582
Opened 2022-02-28 14:28 UTC by veggiematts

Asks the user to provide a robust enough password on password change.

The following rules are implemented:

 - the password must be at least 8 characters long.
 - the password must contain at least one digit.
 - the password must contain at least one capital letter.
 - the password must contain at least one lower-case letter.
 - the password must contain at least one special character, from the following
   list: !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
   ( comes from https://owasp.org/www-community/password-special-characters )

Also, the code has been refactored so:

 - the code checking the complexity is the same on client side and server side
   validation.
 - the UI for the password change is the same in "My Account" and Agent edition.

Test plan:

 - Log in with a user with the following rights : Gestion des agents.
 - Check that you can change the password of any agent, only if the complexity
   requirements are met.
 - Check that you cannot change the password without the "Gestion des agents"
   right.
 - Check that you can change your own password on the "My Account" page,
   regardless of your rights.

2022-04-15 13:01 UTC, jeromecombes requested changes
Lorsqu'on tente la modification d'un mot de passe sans respecter les règles, l'erreur s'affiche en rouge : OK
on clique sur annuler, on tente une nouvelle modification : l'erreur est déjà là. Il serait bien de l'effacer sur l'action de fermeture de la modale.

Le formulaire de modification de mot de passe depuis "Mon Compte" n'est plus intégré mais ouvre une modale, dommage.

Le formulaire de modification de mot de passe depuis "Mon Compte" ne demande pas de vérification du mot de passe actuel. Il faudrait restaurer cette fonction.

2022-06-24 08:07 UTC, alexarn commented
Même remarque que Jérôme au sujet de l’effacement des erreurs lorsqu'on ferme la modale. Ça fonctionne lorsqu'on clique sur le bouton annuler. Mais pas sur la croix

2022-06-24 08:09 UTC, alexarn commented
Au sujet de l'absence d'un formulaire intégré dans "Mon compte", ce n'est toujours pas le cas. Comme c'est du fonctionnel je laisse Jérôme trancher.

2022-06-24 08:11 UTC, jeromecombes commented
> 

Pour info, il existe une propriété onclose (ou qq chose de ce type) qui permet de déclencher une action lorsque la modale se ferme, quel qu’en soit la raison (boutons annuler, valider, ou croix)

2022-06-24 08:16 UTC, veggiematts commented
"Le formulaire de modification de mot de passe depuis "Mon Compte" n'est plus intégré mais ouvre une modale, dommage."

=> Pas sûr que ce soit dommage. En terme d'UX, si on retrouve une même fonctionnalité à plusieurs endroits dans une application, cette fonctionnalité devrait avoir la même apparence, sinon c'est confus pour l'utilisateur.

"Même remarque que Jérôme au sujet de l’effacement des erreurs lorsqu'on ferme la modale. Ça fonctionne lorsqu'on clique sur le bouton annuler. Mais pas sur la croix"

Au temps pour moi, je vais faire un follow-up.

2022-07-19 13:51 UTC, jeromecombes commented
@veggiematts Un client nous demande un minimum de 12 caractères. Peux-tu rendre la longueur paramétrable ? Il serait bien d'ajouter une contrainte pour empêcher de choisir une valeur inférieure à 8.

2022-07-27 08:59 UTC, jeromecombes requested changes
Please see https://suivi.biblibre.com/view.php?id=29957#c212941

2022-08-05 07:36 UTC, jeromecombes requested changes
Tests du 5 août : 
des erreurs ont été trouvées sur le lien "changer le login", sur la protection IP Blocker et une variable change_own_password non définie
Voir détail sur le ticket MT29957

2022-08-05 07:38 UTC, jeromecombes commented
> Please see https://suivi.biblibre.com/view.php?id=29957#c212941

Corrigé par le commit a8d292d90c357fdfb09fb43a14c0147b724a3653

2022-10-14 08:17 UTC, jeromecombes approved these changes

2022-10-14 08:17 UTC, jeromecombes approved these changes
revue : OK
tests : OK
PR 582 approuvée pour master

2022-10-14 11:53 UTC, merged

2022-10-14 11:55 UTC, alexarn commented
Merged on master