New Planno theme
PlanningBiblio/PlanningBiblio pull request #606
Opened 2022-04-05 10:02 UTC by alexarn

2022-04-05 14:32 UTC, jeromecombes requested changes
J'ai l'impression que Pierre a ajouté des classes tableSort sur tous les <th> des datatables.
Si c'est le cas : une solution plus simple et plus propre : 
* en css : `table.datatable th { ... } `
* en template : pas de modif, la class tableSort n'est pas nécessaire

2022-04-05 14:32 UTC, jeromecombes commented on templates/position/index.html.twig
>        </tr>
Simple quotes sur les lignes précédentes

2022-04-05 14:32 UTC, jeromecombes commented on templates/conges/add.html.twig
> +        <td style='color:#cd1b19;'>
remplacer `style='color:#cd1b19;'` par `class='red'`

2022-04-05 14:32 UTC, jeromecombes commented on templates/framework/edit_lines.html.twig
> +            <td style='width:150px;' class="textAlignRight"><label for='nom'>Nom</label></td>
simple quotes

2022-04-05 14:32 UTC, jeromecombes commented on templates/framework/index.html.twig
> +              <th class="tableSort">Site</th>
Simple quotes

2022-04-05 14:32 UTC, jeromecombes commented on templates/myAccount.html.twig
> +              <th class="tableSort">Commentaires</th>
Simple quotes 3 lignes précédentes

2022-04-05 14:32 UTC, jeromecombes commented on templates/position/edit.html.twig
> +    <div class="admin-div">
idem

2022-04-05 14:32 UTC, jeromecombes commented on templates/statistics/absence.html.twig
> +  <div id="content-form">
Simple quotes

2022-04-05 14:32 UTC, jeromecombes commented on templates/statistics/absence.html.twig
> +    <div class="statistics-div">
idem

2022-04-06 08:10 UTC, jeromecombes requested changes
J'ai supprimé mes demandes "simple quotes"

2022-04-06 08:31 UTC, pierrefagot commented on public/conges/recup_pose.php
> +echo "</td><td style='color:#cd1b19;'>\n";
Done :
commit f9ac047486412c252150d314545cf2fb32c4f2b6

2022-04-06 08:41 UTC, pierrefagot commented on public/personnel/hours_tables.php
> +        $hours_tab .= "<td '>Début de pause</td><td '>Fin de pause</td>";
Done :
commit b863e4d77b9db3ab4718692aaebd2596280101fc

2022-04-06 08:41 UTC, pierrefagot commented on public/personnel/hours_tables.php
> +        $hours_tab .= "<td '>Début de pause 2</td><td '>Fin de pause 2</td>";
Done :
commit b863e4d77b9db3ab4718692aaebd2596280101fc

2022-04-06 08:42 UTC, pierrefagot commented on public/personnel/hours_tables.php
> +    $hours_tab .= "<td '>Heure de départ</td>";
Done :
commit b863e4d77b9db3ab4718692aaebd2596280101fc

2022-04-06 08:42 UTC, pierrefagot commented on public/personnel/hours_tables.php
> +    $hours_tab .= "<td '>Temps</td>";
Done :
commit b863e4d77b9db3ab4718692aaebd2596280101fc

2022-04-06 09:23 UTC, pierrefagot commented on public/planning/poste/index.php
> +        echo "<h3 style='text-align:left;margin:40px auto 0 auto; width: 90%;'>Liste des absents</h3>\n";
Le style dans ces h3 est spécifique, il permet de positionner les titres des tableaux absents/présents. 
Différents du positionnement des titres de pages.
Peut-être faire une classe.

2022-04-06 09:23 UTC, pierrefagot commented on public/planning/poste/index.php
> +        echo "<h3 style='text-align:left;margin:40px auto 0 auto; width: 90%;'>Liste des absents</h3>\n";
idem

2022-04-06 09:33 UTC, pierrefagot commented on public/statistiques/postes.php
> +echo "<table class='satistics-div' style='background: #FFF; border-radius: 5px; padding: 10px; width: 100%;'><tr style='vertical-align:top;'><td id='stat-col1'>\n";
Done : 
Faute de frappe, il manque un t à statistic-div 
commit df7ed7613dcb71920a392c3ac4c1fc55c9d0f7a3

2022-04-06 09:51 UTC, pierrefagot commented on templates/absences/index.html.twig
> +              <label >Fin :</label>
Done :
commit abc28afa2b0e518e4399d4e4448df511a4961050

2022-04-06 09:51 UTC, pierrefagot commented on templates/absences/index.html.twig
> +                  <label >Agent :</label>
Done :
commit abc28afa2b0e518e4399d4e4448df511a4961050

2022-04-06 09:52 UTC, pierrefagot commented on templates/absences/index.html.twig
> +        </tr>
Done :
commit abc28afa2b0e518e4399d4e4448df511a4961050

2022-04-06 10:05 UTC, pierrefagot commented on templates/absences/infos.html.twig
> +          <td><label >Date de début</label> </td>
Done :
commit 0a391d888d32186db6e68f4ac84f54bb81ea09b6

2022-04-06 10:06 UTC, pierrefagot commented on templates/base.html.twig
>    </head>
Done :
commit bca4a7a4c4c445067e0c540a9491519d2643a66f

2022-04-06 13:26 UTC, pierrefagot commented on templates/absences/reasons.html.twig
>        </div>
Done : 
commit c3bbc9b4704b0de5efb720d46e872019e334ddfd

2022-04-06 14:07 UTC, pierrefagot commented on templates/agents/agent_table_edit.html.twig
> +      <td style="color:#29495C">Login :</td>
Done : 
commit dab8f6bbde34d8d07fa1bca0d391ca065f5cc182

2022-04-06 14:14 UTC, pierrefagot commented on templates/agents/edit.html.twig
> +      <li id="admin"><a href='#temps' id='personnel-a-li3'>Heures de pr&eacute;sence</a></li>
Done : 
commit e646529c6cdec6e39336db926e71badbaf1b3220

2022-04-06 14:26 UTC, pierrefagot commented on templates/calendar/index.html.twig
>                        {% endif %}
Done : 
commit 29dc0b0eb2807a40e22c5b234e68c7690b317095

2022-04-06 14:29 UTC, pierrefagot commented on templates/conges/add.html.twig
> +        <td style='color:#cd1b19;'>
Done : 
commit 5ac86c042a5ebd64bd5569583793c7501c99f2a9

2022-04-07 09:00 UTC, pierrefagot commented on public/conges/recup_pose.php
> +echo "</td><td style='color:#cd1b19;'>\n";
@alexarn

2022-04-15 13:22 UTC, jeromecombes requested changes
- en ligne 54 du fichier public/personnel/hours_tables.php, il reste un `<td '>`
- @alexarn il faut ajouter un atomic update sur cette PR `UPDATE {$dbprefix}config SET valeur = '' WHERE nom = 'Affichage-theme';`

2022-04-15 13:22 UTC, jeromecombes commented on public/personnel/hours_tables.php
> +    $hours_tab .= "<tr style='text-align:center;'><td style='width:135px;'>{$cellule[$j]}</td><td '>Heure d'arrivée</td>";
`<td '>Heure d'arrivée</td>` --> `<td>Heure d'arrivée</td>`

2022-04-15 14:34 UTC, alexarn commented
Merged on master. For 22.04.xx candidate

2022-04-15 14:34 UTC, closed without merging