Symfonize recup pose
PlanningBiblio/PlanningBiblio pull request #610
Opened 2022-04-06 15:43 UTC by alexarn

2022-04-15 12:47 UTC, jeromecombes requested changes
Pour la symfonisation de la pose des récup, il faut utiliser les mêmes fonctions et templates que pour la pose des congés, avec un param permettra de différencier les informations consultées et à sauvegarder dans la DB. Comme c'est déjà le cas pour l'édition des récup.

Ceci permettra de centraliser le code et permettra au formulaire de pose des récup de bénéficier des avancées du formulaire de pose de congés, comme la validation directe.

2022-07-05 11:44 UTC, alexarn commented
Need to apply MT 37411

2022-09-19 13:35 UTC, jeromecombes commented
Test plan : 
Faire les tests avec ces 2 configs et en mono et multi-sites 
- config1 : Congés : 
- -- Conges-Enable cochée
- -- Conges-Mode = Heures
- -- Conges-Recuperations = Dissocier

- config2 : Congés : 
- -- Conges-Enable cochée
- -- Conges-Mode = Jours
- -- Conges-Recuperations = Dissocier

Pour quelques agents : 
- Dans les fiches des agents, mettre quelques crédits dans le champs "Récupérations" dans l'onglets "Congés". (Si le terme "Récupération n'apparaît pas, mettre des heures dans le dernier champ".
- Créer des plannings de présence pour ces quelques agents

En utilisant les logins de ces agents : 
- cliquer sur le menu Congés / Poser des récupérations
- Tester l'ensemble des possibilités offertes par le formulaire Poser des récupérations, comparer avec master
- Vérifier que les récupérations sont bien enregistrées dans le menu Congés / Liste des récupérations
- Modifier une récupérations, tester l'ensemble des possibilités et comparer avec master

En utilisant un login avec droit de validation des congés niveau 1
- cliquer sur le menu Congés / Poser des récupérations
- poser une récup pour un autre agent avec
- NB : pour le point suivant : le menu validation n'est sans doute pas présent, donc passer ce test dans ce cas.
- - Si le menu "Validation" est présent : pour chaque nouvelle récupération, un enregistrement à l'état demandé, une validation directe niveau 1, un refus niveau 1 (les validation niveau 2 ne doivent pas apparaître)
- Tester l'ensemble des possibilités offertes par le formulaire Poser des récupérations, comparer avec master
- Vérifier que les récupérations sont bien enregistrées dans le menu Congés / Liste des récupérations
- Modifier une récupérations, tester l'ensemble des possibilités et comparer avec master

En utilisant un login avec droit de validation des congés niveau 2
- cliquer sur le menu Congés / Poser des récupérations
- poser une récup pour un autre agents avec 
- NB : pour le point suivant : le menu validation n'est sans doute pas présent, donc passer ce test dans ce cas.
- - Si le menu "Validation" est présent : pour chaque nouvelle récupération, un enregistrement à l'état demandé, une validation directe niveau 1, un refus niveau 1, validation directe niveau 2, refus direct niveau 2.
- Tester l'ensemble des possibilités offertes par le formulaire Poser des récupérations, comparer avec master
- Vérifier que les récupérations sont bien enregistrées dans le menu Congés / Liste des récupérations
- Modifier une récupérations, tester l'ensemble des possibilités et comparer avec master

En utilisant un compte admin (avec droit de validation des congés)
- tester les modifications sans validation
- tester les validations niveau 1 : refus et acceptation
- tester les validations niveau 2 : refus et acceptation
- Si le champs "Motif de refus apparaît, le tester. Comparer le fonctionnement avec master
- Jouer avec les niveaux de validations, dans tous les sens : 
- -- Exemple : un compte avec les droits validation niveau 2 valide la récup. Puis un compte avec seulement le droit validation niveau 1 édite la récup. Il ne devrait pas pouvoir la modifier et le champ "validation" doit rester sur "Valider" (niveau 2).
- Toujours comparer le fonctionnement à master.

2022-10-04 13:41 UTC, alexarn commented
rebased on master

2022-10-28 12:18 UTC, jeromecombes requested changes
Label overtime utilisé à la place de comp_time dans Agentcontroller en ligne 783

2022-10-28 12:18 UTC, jeromecombes commented on src/Controller/AgentController.php
> +                'lang_comp_time'        => $lang['overtime'],
Ici, il faut utiliser `'lang_comp_time' => $lang['comp_time']`, et non `'lang_comp_time' => $lang['overtime'],`

2022-10-31 17:06 UTC, jeromecombes commented on src/Controller/AgentController.php
> +                'lang_comp_time'        => $lang['overtime'],
Corrigé par le commit 59c8df5df07b16fc4b2ae1111b31b52897845e01

2022-12-09 17:28 UTC, jeromecombes approved these changes
revue : OK
tests : OK
PR approuvée avec rebase du jour et les 2 commits ajoutés

2022-12-29 07:51 UTC, alexarn commented
Merged on master

2022-12-29 07:51 UTC, closed without merging