MT 36819: replace all links planningbiblio.fr with planno.fr
PlanningBiblio/PlanningBiblio pull request #679
Opened 2022-06-27 14:31 UTC by alexarn

- Modification of the link to the website in all the files & the readme

2022-07-15 12:55 UTC, jeromecombes requested changes
Typo sur la page accessDenied

2022-07-15 16:20 UTC, jeromecombes requested changes
l'indentation a changé sur plusieurs fichiers avec le 3ème commit : à revoir

2022-07-15 16:28 UTC, jeromecombes approved these changes
J'ai corrigé les erreurs d'indentation et fait un force-push.
PR approuvée
à merger sur 22.04.xx et master

2022-08-19 14:06 UTC, alexarn commented
Merged on master and 22.04.xx

2022-08-19 14:06 UTC, closed without merging