MT37227: CSS optimization
PlanningBiblio/PlanningBiblio pull request #682
Opened 2022-06-27 14:41 UTC by alexarn

Suppression of the tableSort and tableSort-bis Class
	Replaced by table.dataTable th

2022-07-15 12:37 UTC, jeromecombes commented on public/planning/poste/index.php
> +        echo "<th class='dataTableDateFR'>D&eacute;but</th>\n";
Remplacer & eacute; par é sur les 2 lignes précédentes

2022-07-15 12:38 UTC, jeromecombes commented on public/themes/default/default.css
> +}*/
Pourquoi est-ce commenté ?
A supprimer si ce n'est pas utile.

2022-07-15 12:42 UTC, jeromecombes commented on templates/absenceInfo/index.html.twig
> -                    <th class="tableSort">Texte</th>
Sur la plupart des lignes où il n'y avait que cette classe, il y a un espace entre le th et le > : espace à supprimer
Tu peux exécuter la commande suivante pour les repérer : 
`grep -r --exclude-dir={vendor,var,.git} "<th >" *`

2022-07-15 12:47 UTC, jeromecombes commented
Quelques améliorations demandées (& eacute; --> é, code commenté en CSS et espace dans les < th >
Mais les tests sont OK.

2022-07-15 13:55 UTC, jeromecombes requested changes
L'indentation du fichier default.css a été modifiée par erreur.
A revoir.

2022-07-15 16:10 UTC, jeromecombes approved these changes
Revue et tests : OK
à marger sur master et 22.04.xx

2022-11-09 13:01 UTC, alexarn commented
Merged on master. Does not apply on 22.04.xx

2022-11-18 11:07 UTC, jeromecombes commented
merged on master
For 22.04.xx : #779

2022-11-18 11:07 UTC, closed without merging