MT37205: Undo / Redo capabilities
PlanningBiblio/PlanningBiblio pull request #685
Opened 2022-07-01 08:40 UTC by alexarn

2022-07-26 07:11 UTC, jeromecombes requested changes
Dysfonctionnements constatés pendant les tests 
et améliorations demandées
voir ticket MT37205

2022-08-01 15:27 UTC, jeromecombes commented
> 

**Les dysfonctionnements constatés sont corrigés par les 2 commits du 29/07/22.
Les derniers tests sont concluants.**

Reste à voir les optimisations évoquées dans le ticket MT37205, mais elles ne me semblent pas bloquantes.
Dans le code, il y a 2 //TODO Handle rights here.

2022-10-17 12:32 UTC, jeromecombes requested changes
revoir le contrôle CSRF

2022-10-17 12:32 UTC, jeromecombes commented on src/Controller/PlanningJobController.php
>          if (!$date || !$site) {
Pour ne pas utiliser cette fonction `$this->csrf_protection($request);` ?
Voir https://suivi.biblibre.com/view.php?id=33800

2022-10-17 12:32 UTC, jeromecombes commented on src/Controller/PlanningJobController.php
>          if (!$date || !$site) {
Pour ne pas utiliser cette fonction `$this->csrf_protection($request);` ?
Voir https://suivi.biblibre.com/view.php?id=33800

2022-10-17 12:35 UTC, jeromecombes requested changes

2022-10-17 12:35 UTC, jeromecombes commented on public/planning/poste/js/planning.js
> -
Pourquoi retirer le `disableRedo();` ?

Lorsqu'on utilise le menu_div, on doit empêcher le retour en arrière, tel que défini dans le spec.
Sinon, on n'a plus rien de cohérent.

2022-11-02 09:47 UTC, jeromecombes commented on src/Controller/PlanningJobController.php
>          if (!$date || !$site) {
correction approuvée

2022-11-02 21:40 UTC, jeromecombes approved these changes

2022-11-02 21:41 UTC, jeromecombes approved these changes
revue et tests : OK
PR approuvée
@alexarn pourras-tu squasher avant de merger ?
Merci,

2022-11-03 13:06 UTC, merged

2022-11-03 13:06 UTC, alexarn commented
Rebase and merge PR 685