MT 37705: remove Holiday CET
PlanningBiblio/PlanningBiblio pull request #709
Opened 2022-08-26 13:48 UTC by alexarn

2022-08-26 14:15 UTC, jeromecombes requested changes
coquille WEHERE à la place de WHERE dans l'atomic update

2022-08-26 14:15 UTC, jeromecombes commented on public/setup/atomicupdate/MT37705_remove_conges_cet_table.php
> +$sql[] = "DELETE FROM {$dbprefix}acces WEHERE page = 'conges/cet.php';";
--> $sql[] = "DELETE FROM {$dbprefix}acces WHERE page = 'conges/cet.php';";

2022-08-26 14:18 UTC, jeromecombes approved these changes

2022-08-29 12:12 UTC, alexarn commented
Merged on master

2022-08-29 12:12 UTC, closed without merging