MT 38196: Symfonyze week planning
PlanningBiblio/PlanningBiblio pull request #728
Opened 2022-09-22 14:25 UTC by alexarn

2022-11-08 09:48 UTC, jeromecombes requested changes

2022-11-08 09:48 UTC, jeromecombes commented on init/init.php
>  // Recupération des droits d'accès de l'agent
Je perds l'information suivante en session : "la dernière page consultée est la vue semaine" 
Ce qui fait que lorsque je navigue vers un autre menu et que je reviens sur le planning, je ne tombe plus sur la vue semaine.
cf : note 1./ du ticket MT38196

2022-11-08 09:48 UTC, jeromecombes commented on public/include/menu.php
>      $active = (in_array($page, ['conges/recup_pose.php', 'conges/infos.php', 'conges/credits.php']) and $menu[$key][0]['titre'] == 'Congés') ? 'active' : $active;
Attention au conflit lors de l'intégration sur master.
Les agents volants ont été symfonisés depuis. ce qui fait que la page planning/colants/index.php n'existe plus sur master et que logiquement toute la condition de la ligne 85 peut être supprimée

Il faudra cependant définir $active = null; soit sur la ligne 85, soit en modifiant la ligne 86 pour qu'elle termine par `? 'active' : null;`

2022-11-08 09:48 UTC, jeromecombes commented on templates/planning/poste/menu.html.twig
> +                <td style="font-size: 13pt;"> / <a href='{{ base_url }}/week' class="{{ week_view ? 'menuRed' : 'menu' }}" >Semaine</a></td>
Il faut utiliser la fonction asset à la place de base_url 
et remplacer toutes les occurrences base_url par asset dans ce fichier maintenant qu'il est toujours chargé par Symfony.
réf : https://wiki.biblibre.com/doc:planningbiblio:rules#fonction_asset

2022-11-08 10:04 UTC, jeromecombes commented on templates/planning/poste/menu.html.twig
> +                <td style="font-size: 13pt;"> / <a href='{{ base_url }}/week' class="{{ week_view ? 'menuRed' : 'menu' }}" >Semaine</a></td>
Corrigé par f75555f4a515fc71090a2786c6b1206e260880f8

2022-11-09 08:06 UTC, jeromecombes requested changes

2022-11-09 08:06 UTC, jeromecombes commented on public/index_symfony.php
> +
Ceci devrait être géré dans IndexController.php avec un return $this->redirectToRoute('xxx');
Je teste pour voir ce que ça donne

2022-11-09 08:52 UTC, jeromecombes approved these changes
Approuvée avec les  derniers commit (272d7ca5b4fcd2d88ee41c5ba1b8c4d6e2a9cac9 et 272d7ca5b4fcd2d88ee41c5ba1b8c4d6e2a9cac9)

2022-11-09 08:52 UTC, jeromecombes commented on init/init.php
>  // Recupération des droits d'accès de l'agent
corrigé par 272d7ca5b4fcd2d88ee41c5ba1b8c4d6e2a9cac9

2022-11-09 08:52 UTC, jeromecombes commented on public/index_symfony.php
> +
corrigé par 272d7ca5b4fcd2d88ee41c5ba1b8c4d6e2a9cac9

2022-11-15 14:34 UTC, alexarn commented
Merged on master

2022-11-15 14:34 UTC, closed without merging