MT 38321: Make toHis method don't transform sites in working hours
PlanningBiblio/PlanningBiblio pull request #735
Opened 2022-09-26 15:00 UTC by alexarn

2022-10-04 11:25 UTC, jeromecombes requested changes

2022-10-04 11:25 UTC, jeromecombes commented on src/PlanningBiblio/Helper/HourHelper.php
OK, pour cette correction qui correspond à ce que nous avons sur la branche 22.04.xx
Mais je ne comprend pas l’intérêt de ce test. Le test suivant transforme en H:i:s si le format n'est pas H:i:s (donc si le format attendu n'est pas le bon, on transforme au bon format). Selon moi, ça couvre également le cas précédent (! H:i) avec en plus la transformation (donc mieux).
à corriger également le TU qui ne passe pas.

2022-10-14 08:57 UTC, jeromecombes approved these changes

2022-10-14 08:58 UTC, jeromecombes approved these changes
Revue : OK
**Attente de l'ajout des commentaires expliquant les tests sur le fichier src/PlanningBiblio/Helper/HourHelper.php**
Tests : OK
PR approuvée

2022-10-14 09:04 UTC, jeromecombes approved these changes
revue : OK,
tests : OK
commentaires : OK
PR à merger sur master

2022-10-14 09:08 UTC, alexarn commented
Merged on master

2022-10-14 09:08 UTC, closed without merging