MT 38757: restore access to planning and page for anonymous users
PlanningBiblio/PlanningBiblio pull request #782
Opened 2022-11-21 14:35 UTC by alexarn

See MT 38757

2022-11-21 14:41 UTC, jeromecombes approved these changes
revue et tests : OK
PR Approuvée

2022-11-22 07:12 UTC, jeromecombes requested changes
@alexarn 
j'y ai repensé suite à ta remarque sur la restauration des ID 99.
Je pense que c'est la meilleure chose à faire.
Dans ce cas, le Listener devrait traiter ces pages et les droits d'accéder comme les autres, sans conditions particulières. Ce qui simplifierai le code et sa compréhension.

Tous les agents créés dans Planno ont à minima les droits 99 et 100 : c'est donc corrects de ce côté.
Concernant les tests unitaires, il manque peut être le droits 99 en session ou dans la variable $droits (je n'ai pas vérifié).

2022-11-22 08:39 UTC, jeromecombes approved these changes
J'ai testé en rétablissant le droit 99 et ça ne fonctionne pas.
Donc OK pour intégrer la PR actuelle

2022-11-22 08:41 UTC, alexarn commented
Merged on master and 22.10.xx

2022-11-22 08:41 UTC, closed without merging