MT 39022: take absences for remote working into account when notifying in plannings
PlanningBiblio/PlanningBiblio pull request #784
Opened 2022-11-22 16:13 UTC by alexarn

See MT 39022

2022-11-22 16:25 UTC, jeromecombes commented on public/planning/poste/class.planning.php
> +                if ($elem["absent"] ==  1 && $position && $position['teleworking'] == 1) {
Sans avoir testé : 
Tu peux sans doute simplifier par 
`if ($elem["absent"] ==  1 && !empty($position['teleworking'])) { `
Car si position n'existe pas, !empty retournera false
et si $position['teleworking'] = 0, !empty retournera false également.
Donc !empty retournera true seulement si $position existe et $position['teleworking'] == 1

2022-11-22 16:28 UTC, jeromecombes commented on public/planning/poste/class.planning.php
> +                    $teleworking_exception = (!empty($teleworking_reasons) and is_array($teleworking_reasons))
Le test is_array ne me semble pas nécessaire, 
Si je ne me trompe pas, entityManager->getRepository renvoie toujours un tableau, complet ou vide.

2022-11-22 16:35 UTC, jeromecombes commented on public/planning/poste/class.planning.php
> +                    }
J'ai peur que ce système mette $elem["absent"] à 0 dès qu'il y a une absence pour télétravail sur le créneau.
Que ce passe-t-il s'il y a une absence télétravail + une absence maladie ?
Dans ce cas, on doit rester sur $elem["absent"] = 1

2022-12-06 10:39 UTC, jeromecombes requested changes

2022-12-06 10:39 UTC, jeromecombes commented on public/planning/poste/class.planning.php
> +            $db->select('absences', '*', "`debut`<'$end' AND `fin`>'$start' AND `perso_id`='$id' $filter ");
TESTS : Les absences non-validées sont prises en compte alors qu'elles en devraient pas l'être.
Il faut ajouter AND valide  > 0

2022-12-06 10:54 UTC, jeromecombes commented on public/planning/poste/class.planning.php
> +                if ($elem["absent"] ==  1 && $position && $position['teleworking'] == 1) {
corrigé par 19af411670077079a5279fe548dc45714e77f7df

2022-12-06 10:55 UTC, jeromecombes commented on public/planning/poste/class.planning.php
> +                    $teleworking_exception = (!empty($teleworking_reasons) and is_array($teleworking_reasons))
corrigé par 19af411670077079a5279fe548dc45714e77f7df

2022-12-06 10:55 UTC, jeromecombes commented on public/planning/poste/class.planning.php
> +                    }
corrigé par 19af411670077079a5279fe548dc45714e77f7df

2022-12-06 10:55 UTC, jeromecombes approved these changes
revue : OK
tests : OK
PR approuvée

2022-12-29 07:39 UTC, alexarn commented
Merged on master, 22.10.xx and 22.04.xx

2022-12-29 07:39 UTC, closed without merging