Adapt holidays reseting cron jobs
PlanningBiblio/PlanningBiblio pull request #806
Opened 2022-12-07 13:22 UTC by alexarn

See MT 37569

2022-12-08 08:53 UTC, alexarn commented on src/Cron/Crontab.php
> +        $last = date('Y-m-d H:i:s');
À retirer

2022-12-20 10:00 UTC, jeromecombes requested changes

2022-12-20 10:00 UTC, jeromecombes commented on public/index_symfony.php
> +if (isset($_SESSION['login_id'])) {
Il faut remplacer ceci par if (!empty($_SESSION['login_id'])) {
Comme ça a été fait sur public/index.php (correction apportée depuis la création de cette PR pour éviter le déclenchement infructueux des crons et les erreurs CSRF dans les logs)

2022-12-20 13:05 UTC, jeromecombes requested changes

2022-12-20 13:05 UTC, jeromecombes commented on src/Cron/Legacy/cron.holiday_reset_comp_time.php
> +        $c->maj($credits, "modif", true);
Il faut passer un tableau $credits complet avec les index conges_credit, comp_time, conges_anticipation et conges_reliquat même si certaines valeurs ne sont pas modifiées

foreach ($p->elements as $elem) {
    $credits=array();
    $credits['comp_time'] = 0;
    $credits['conges_credit'] = $elem['conges_credit'];
    $credits['conges_anticipation'] = $elem['conges_anticipation'];
    $credits['conges_reliquat'] = $credits['conges_reliquat'];
}

2022-12-20 13:05 UTC, jeromecombes commented on src/Cron/Legacy/cron.holiday_reset_credits.php
> +        }
Il faut garder $credits['comp_time'] même si la valeur n'est pas modifiée : 

`$credits['comp_time'] = $elem['comp_time'];`

2022-12-20 13:05 UTC, jeromecombes commented on src/Cron/Legacy/cron.holiday_reset_credits.php
> +}
Voir s'il ne serait pas plus clair de tout réunir sous la même condition `if ($config['Conges-transfer-comp-time'])`

2022-12-20 14:09 UTC, jeromecombes commented on public/index_symfony.php
> +if (isset($_SESSION['login_id'])) {
Corrigé par le commit dca5bdf0256d6babbb3399cbc9affa7dd0f7f638

2022-12-20 14:10 UTC, jeromecombes commented on public/setup/atomicupdate/MT37569.php
> +    $sql[] = "ALTER TABLE `{$dbprefix}cron` ADD COLUMN `disabled` ENUM('0','1') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '0' AFTER `last`;";
Corrigé par le commit 0328eca3cb50271672225008aa02188dbb9165a4

2022-12-20 14:11 UTC, jeromecombes commented on src/Cron/Legacy/cron.holiday_reset_comp_time.php
> +        $c->maj($credits, "modif", true);
corrigé par le commit 457c722076c3a1a82f0182c517ced4f77f4a418f

2022-12-20 14:12 UTC, jeromecombes commented on src/Cron/Legacy/cron.holiday_reset_credits.php
> +        }
Corrigé par le commit 457c722076c3a1a82f0182c517ced4f77f4a418f

2022-12-20 14:24 UTC, jeromecombes commented on src/Cron/Crontab.php
> +        $last = date('Y-m-d H:i:s');
Corrigé par 1d229510f0ebcbb6b7c6e688cbb1f4110a399bb7

2022-12-20 14:25 UTC, jeromecombes commented on src/Cron/Crontab.php
> +
amélioré par 1d229510f0ebcbb6b7c6e688cbb1f4110a399bb7

2022-12-20 16:53 UTC, jeromecombes commented on src/Cron/Legacy/cron.holiday_reset_credits.php
> +}
Après vérification, il vaut mieux garder le code tel qu'il est actuellement

2022-12-20 17:12 UTC, jeromecombes commented on public/setup/atomicupdate/MT37569.php
> +    $sql[] = "ALTER TABLE `{$dbprefix}cron` ADD COLUMN `disabled` ENUM('0','1') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '0' AFTER `last`;";
corrigé par 84216eca2baeb8aec38d3797704254fb22618ddc

2022-12-20 17:12 UTC, jeromecombes commented on public/setup/db_structure.php
> +  `disabled` ENUM('0','1') NOT NULL DEFAULT '0',
corrigé par 84216eca2baeb8aec38d3797704254fb22618ddc

2022-12-20 17:13 UTC, jeromecombes commented on src/Model/Cron.php
> +    }
corrigé par corrigé par 84216eca2baeb8aec38d3797704254fb22618ddc

2022-12-20 17:13 UTC, jeromecombes commented on src/Cron/Crontab.php
> +
corrigé par 84216eca2baeb8aec38d3797704254fb22618ddc

2022-12-20 17:15 UTC, jeromecombes approved these changes
revue : OK avec les commits du jour.
TESTS : OK
PR approuvée pour master et 22.10.xx
Squasher avant d'intégrer SVP

2022-12-20 17:29 UTC, jeromecombes commented
replaced with #821

2022-12-20 17:29 UTC, closed without merging