MT 39300: update sites when changing agent on workinghour copy form
PlanningBiblio/PlanningBiblio pull request #830
Opened 2023-01-04 15:54 UTC by alexarn

2023-01-06 14:44 UTC, jeromecombes requested changes
Tests : 

Avec le correctif, lors de la copie les colonnes sites et le menu "validation" s'actualise bien, mais l'ensemble des planning se vide, ainsi que les date de début et de fin.
Ce n'est pas le comportement souhaité, on perd l'intérêt de la copie.

En faisant un revert du commit "MT 39300: update validation statuses when changing agent on workinghour copy form",
on retrouve un comportement "normal". La copie est OK, seul le menu de validation ne s'actualise pas.
--> Il faut donc garder le return false pour empêcher le rechargement du formulaire en cas de copie, et le commentaire associé (qui peut être complété d'un lien vers ce ticket).
--> Et trouver une autre solution (Ajax) pour actualiser le menu de validation.

2023-01-16 16:53 UTC, jeromecombes approved these changes
J'approuve **sans le commit "MT 39300: update validation statuses ..."** qui casse les copies.
Ceci pourra être traité dans un autre ticket.

2023-01-16 16:55 UTC, jeromecombes commented
Force push = rebase master pour supprimer l'erreur sur le TU OvertimeController

2023-01-19 15:19 UTC, alexarn commented
Merged on master and 22.10.xx

2023-01-19 15:19 UTC, closed without merging