Added unit tests for password change with csrf protection
PlanningBiblio/PlanningBiblio pull request #847
Opened 2023-01-11 16:03 UTC by alexarn

2023-01-11 16:25 UTC, alexarn reviewed
Lot of tab added

2023-01-11 16:25 UTC, alexarn commented on src/Controller/AgentController.php
> +
Blank line

2023-01-11 16:25 UTC, alexarn commented on src/Controller/AgentController.php
> +            }
Indentation

2023-01-11 16:25 UTC, alexarn commented on src/Controller/AgentController.php
> +            }
Indentation

2023-01-11 16:25 UTC, alexarn commented on src/Controller/AgentController.php
> +
blank line

2023-01-11 16:25 UTC, alexarn commented on src/Controller/AgentController.php
> +
blank line

2023-01-11 16:25 UTC, alexarn commented on src/Controller/BaseController.php
> +
blank line

2023-01-11 16:25 UTC, alexarn commented on src/Controller/PlanningJobController.php
> +
tab ?

2023-01-11 16:25 UTC, alexarn commented on src/Controller/PlanningJobController.php
> +
tab ?

2023-01-11 16:25 UTC, alexarn commented on src/Controller/PlanningJobController.php
> +
tab ?

2023-01-11 16:25 UTC, alexarn commented on src/Controller/PlanningJobController.php
> +
tab ?

2023-01-11 16:25 UTC, alexarn commented on src/Controller/PlanningJobController.php
> +
tab ?

2023-01-11 16:25 UTC, alexarn commented on src/Controller/PlanningJobController.php
> +
tab ?

2023-01-11 16:25 UTC, alexarn commented on src/Controller/PlanningJobController.php
> +
tab ?

2023-01-11 16:25 UTC, alexarn commented on src/Controller/PlanningJobController.php
> +
tab ?

2023-01-11 16:25 UTC, alexarn commented on src/Controller/PlanningJobController.php
> +
tab ?

2023-01-11 16:25 UTC, alexarn commented on src/Controller/PlanningJobController.php
> +
tab ?

2023-01-11 16:25 UTC, alexarn commented on src/Controller/PlanningJobController.php
> +
tab ?

2023-03-22 08:33 UTC, jeromecombes reviewed
A tester.
Vérifier le fonctionnement des redirectToRoute, notamment sur les actions réalisées en Ajax

2023-03-22 08:33 UTC, jeromecombes commented on src/Controller/PlanningJobController.php
> +            return $this->redirectToRoute('access-denied');
A tester
Je ne pense pas que le redirect soit adapté car nous sommes ici en ajax

2023-03-22 08:33 UTC, jeromecombes commented on src/Controller/PlanningJobController.php
> +            return $this->redirectToRoute('access-denied');
A tester
Je ne pense pas que le redirect soit adapté car nous sommes ici en ajax

2023-03-22 08:33 UTC, jeromecombes commented on src/Controller/AgentController.php
> +            return $this->redirectToRoute('access-denied');
Il s'agit de l'ajout demandé dans MT37706

2023-03-29 08:51 UTC, jeromecombes requested changes

2023-03-29 08:51 UTC, jeromecombes commented on src/Controller/PlanningJobController.php
> +            return $this->redirectToRoute('access-denied');
La requête ajax est redirigée.
Le popup erreur "Impossible de répéter la dernière action. Une erreur s'est produite" s'affiche.
C'est correct

2023-03-29 08:51 UTC, jeromecombes commented on src/Controller/PlanningJobController.php
> +            return $this->redirectToRoute('access-denied');
La requête ajax est redirigée.
Le popup erreur "Impossible de répéter la dernière action. Une erreur s'est produite" s'affiche.
C'est correct

2023-03-29 08:51 UTC, jeromecombes commented on src/Controller/AgentController.php
> +        }
TESTS : Le blocage est réel mais l'utilisateur n'est pas averti car la requête est faite en ajax et il n'y a pas de retour sur le formulaire.
Il y a une redirection vers /access-denied avec le statut 403 sur la requête en arrière plan.
Il serait préférable d'avoir une réponse JSON qui soit traitée pour afficher l'erreur dans le formulaire.

2023-03-29 08:51 UTC, jeromecombes commented on src/Controller/AgentController.php
> +        }
Il est sans doute préférable de garder le redirectToRoute mais de faire en sorte que ce soit détectée et affiché en erreur, comme ce qui est fait pour undo / redo.

2023-03-29 08:51 UTC, jeromecombes commented on src/Controller/AgentController.php
> +            return $this->redirectToRoute('access-denied');
Impossible de modifier le login même si le jeton est correct.
Il manque probablement la fourniture du jeton à la route ajax

2023-03-29 08:51 UTC, jeromecombes commented on src/Controller/AgentController.php
> +            return $this->redirectToRoute('access-denied');
Test après ajout de passage du jeton : OK
avec bon token : OK
avec mauvais token : popup erreur "Une erreur est survenue lors de la modification du login." : OK

2023-03-29 08:51 UTC, jeromecombes commented on templates/agents/elements/change_password_div.html.twig
> +      <form id="change-password">
Le id="change-password" ne me semble pas nécessaire.
Il a été retiré lors du rebase

2023-03-29 08:54 UTC, jeromecombes commented
force push : rebase master

2023-03-29 10:33 UTC, jeromecombes commented on src/Controller/AgentController.php
> +        }
Corrigé par 8dd507c5abf6991c390b1fe35aa86c5fc2d75865

2023-03-29 10:33 UTC, jeromecombes approved these changes
revue, tests, corrections : OK
approuvée pour master

2023-03-29 12:09 UTC, jeromecombes commented
replaced with the squashed branch #895

2023-03-29 12:10 UTC, closed without merging