MT40420: Don't add the free break if the holiday is on a full day
PlanningBiblio/PlanningBiblio pull request #913
Opened 2023-05-23 09:44 UTC by veggiematts

Test plan:

 - For an agent that has working hours from 14:00 to 18:00 and one hour of free break (which starts at 12 and ends at 14), add a full day holiday

 - Without the patch, counted hours are 5 (incorrect)

 - With the patch, counted hours are 4 (correct)

2023-06-06 09:43 UTC, LucyMichel commented
Test ok sur MT40420

2023-06-13 12:03 UTC, jeromecombes requested changes
Je n'approuve pas la PR 913.

Le test suivant échoue avec cette PR alors qu'il est OK sans :
- L'agent travaille de 9h à 17h avec une heure de pause libre le lundi. La journée vaut 7h.
- Il pose un congé sur le lundi :
-- Sans la PR : il calcule 7h : OK
-- Avec la PR : il calcule 8h : KO

2024-05-17 07:55 UTC, jeromecombes approved these changes

2024-05-28 07:43 UTC, jeromecombes commented
PR 913 mergée sur master, 23.10.xx et 24.04.xx

2024-05-28 07:43 UTC, closed without merging