MT41030: Allow to narrow ICS exports to a number of days in the past
PlanningBiblio/PlanningBiblio pull request #922
Opened 2023-06-08 09:26 UTC by veggiematts

A new configuration is added: ICS-Interval, which is the number of days in the past to export ICS calendars from.
    
If ICS-Interval is not set, or set to a value that is not an integer, all events and/or absences in the past will be exported.

Regardless of ICS-Interval configuration, events in the future are still exported as before.

The configuration option ICS-Interval can be overridden by adding an interval parameter to the calendar URL:
    
 Example: <URL>&interval=10

2023-06-08 14:00 UTC, jeromecombes requested changes

2023-06-09 10:03 UTC, veggiematts commented on public/ics/calendar.php
> +if ($interval_get != '' && intval($interval_get)) {
Non, car le résultat de filter_input est une string: is_integer($interval_get) sera toujours faux.

if (is_integer((int) $interval_get) fonctionne mais est-ce que c'est plus lisible que d'utiliser intval ? 

De plus, le test en lui-même renvoie vrai quand le paramètre n'est pas fourni, ce qui n'est pas ce qu'on veut.

2023-06-09 10:03 UTC, veggiematts commented on public/ics/calendar.php
> +if ($config['ICS-Interval'] != '' && intval($config['ICS-Interval'])) {
Non, car $config['ICS-Interval'] est une string: is_integer($config['ICS-Interval']) sera toujours faux.

is_integer((int) $config['ICS-Interval']) fonctionne mais est-ce que c'est plus lisible que d'utiliser intval ?

2023-06-09 12:19 UTC, jeromecombes commented on public/ics/calendar.php
> +if ($interval_get != '' && intval($interval_get)) {
OK, merci pour tes retours.
Je teste dès que possible

2023-06-12 14:58 UTC, jeromecombes approved these changes
Les tests fonctionnels sont OK.
PR approuvée pour master

2023-06-29 12:49 UTC, merged