MT40653: Right copy does not return to top of page
PlanningBiblio/PlanningBiblio pull request #999
Opened 2024-02-05 10:52 UTC by jeromecombes

MT40653: Right copy does not return to top of page

2024-02-08 09:56 UTC, veggiematts requested changes

2024-02-08 09:56 UTC, veggiematts commented on public/planning/poste/fonctions.php
> +    $cellule .= '<a class="pl-icon arrow-right"></a>';
I would perhaps add role="button" for accessibility:
`$cellule .= '<a class="pl-icon arrow-right" role="button"></a>';`
See https://developer.mozilla.org/fr/docs/Web/Accessibility/ARIA/Roles/button_role

2024-02-08 09:56 UTC, veggiematts commented on public/planning/poste/js/planning.js
> +      $("#td"+cellule).append('<a class="pl-icon arrow-right"></a>');
I would perhaps add role="button" for accessibility:
`$("#td"+cellule).append('<a class="pl-icon arrow-right" role="button"></a>');`
See https://developer.mozilla.org/fr/docs/Web/Accessibility/ARIA/Roles/button_role

2024-02-08 10:33 UTC, veggiematts approved these changes

2024-02-09 09:11 UTC, jeromecombes commented
Merged

2024-02-09 09:11 UTC, closed without merging